### ISSUE TITLE
--cache index.cache.txt

### ISSUE THREAD

**Issue by ndaniel** [pmelsted/pizzly#1]
Hello,

what exactly is the file `index.cached.txt` from:
```
pizzly \
-k 31 \
--gtf index.gtf \
--cache index.cache.txt \
--align-score 2 \
--insert-size 250 \
--fasta index.fa.gz \
--output test output/fusion.txt
```
Is it an input file or an output file? How can I get one?

Cheers,
Daniel

**Comment by pmelsted** [comment]
It is a sane gtf format. If it doesn't exist the gtf is parsed and this file is created. If it exists the gtf is not parsed and we read this one instead. 

Need to document this, thanks for reminding me

- Páll

**Comment by ndaniel** [comment]
Indeed it is an output file!
