### ISSUE TITLE
How does pizzly work ?

### ISSUE THREAD

**Issue by ahy1221** [pmelsted/pizzly#10]
Very interesting software. But how does this tool work? 
I guess you do assemble all possible fusion transcripts sequence according to  GTF reference and do the quantification for these transcripts to see whether they are expressed?

**Comment by pmelsted** [comment]
Pizzly is based on detecting reads that span fusion junctions to call potential fusions. Once the fusion sequences are called kallisto can be used to quantify the expression of potential fusions. An example of this workflow is in the Snakefile in the test directory.

The preprint describing the details is coming soon.
