### ISSUE TITLE
Non-printable characters (including ASCII 0) in fusion output FASTA sequences

### ISSUE THREAD

**Issue by kreil** [pmelsted/pizzly#11]
In a recent run, we got about ten instances where there are non-printable characters in the fusion output FASTA sequences. I rechecked, that cannot come from the sequences in the original FASTA reference file.

Is anyone else seeing this? Any ideas? I paste an example below - the non-printable characters are rendered as "^X" where X is a printable characters. "^@" for instance stands for ASCII character zero.

>ENST00000409917_0:788_ENST00000370321_-10:1043
TCCTCGCAGGACCTCATGAGTAAGCTGTGGCGGCGTGGGAGCACCTCTGGGGCTATGGAGGCCCCTGAGCCGGGAGAAGCCCTGGAGTTGAGCCTGGCGGGTGCCCATGGCCATGGAGTGCACAAGAAAAAACACAAGAAGCACAAGAAGAAACACAAGAAGAAACACCATCAGGAAGAAGACGCCGGGCCCACGCAGCCGTCCCCTGCCAAGCCTCAGCTCAAACTCAAAATCAAGCTTGGGGGACAAGTCCTGGGGACCAAGAGTGTTCCTACCTTCACTGTGATCCCAGAGGGGCCTCGCTCACCCTCTCCCCTTATGGTTGTGGATAATGAAGAGGAACCTATGGAAGGAGTCCCCCTTGAGCAGTACCGTGCCTGGCTGGATGAAGACAGTAATCTCTCTCCCTCTCCACTTCGGGACCTATCAGGAGGGTTAGGGGGTCAGGAGGAAGAGGAGGAACAGAGGTGGCTGGATGCCCTGGAGAAGGGGGAGCTGGATGACAATGGAGACCTCAAGAAGGAGATCAATGAGCGGCTGCTTACTGCTCGACAGAGGAGATGCTGCTGAAGCGCGAGGAGCGGGCGCGGAAGCGGCGGCTCCAGGCGGCGCGGCGGGCAGAAGAGCACAAGAACCAGACTATCGAGCGCCTCACCAAGACTGCGGCGACCAGTGGGCGGGGAGGCCGGGGGGGCGCACGGGGCGAGCGGCGGGGAGGGCGGGCTGCGGCTCCGGCCCCCATGGTGCGCTACTGCAGCGGAGCACAGGGTTCCACCCTTTCCTTCCCA^@^@1^F^@^@
^@^@^@^@CGCAAGGGCTGTGGCCCTTTTCCCACCCCCTAGCGCCGCTGGGCCTGCAGGTCTCTGTCGAGCAGCGGACGCCGGTCTCTGTTCCGCAGGATGGGGTTTGTTAAAGTTGTTAAGAATAAGGCCTACTTTAAGAGATACCAAGTGAAATTTAGAAGACGACGAGAGGGTAAAACTGATTATTATGCTCGGAAACGCTTGGTGATACAAGATAAAAATAAATACAACACACCCAAATACAGGATGATAGTTCGTGTGACAAACAGAGATATCATTTGTCAGATTGCTTATGCCCGTATAGAGGGGGATATGATAGTCTGCGCAGCGTATGCACACGAACTGCCAAAATATGGTGTGAAGGTTGGCCTGACAAATTATGCTGCAGCATATTGTACTGGCCTGCTGCTGGCCCGCAGGCTTCTCAATAGGTTTGGCATGGACAAGATCTATGAAGGCCAAGTGGAGGTGACTGGTGATGAATACAATGTGGAAAGCATTGATGGTCAGCCAGGTGCCTTCACCTGCTATTTGGATGCAGGCCTTGCCAGAACTACCACTGGCAATAAAGTTTTTGGTGCCCTGAAGGGAGCTGTGGATGGAGGCTTGTCTATCCCTCACAGTACCAAACGATTCCCTGGTTATGATTCTGAAAGCAAGGAATTTAATGCAGAAGTACATCGGAAGCACATCATGGGCCAGAATGTTGCAGATTACATGCGCTACTTAATGGAAGAAGATGAAGATGCTTACAAGAAACAGTTCTCTCAATACATAAAGAACAGCGTAACTCCAGACATGATGGAGGAGATGTATAAGAAAGCTCATGCTGCTATACGAGAGAATCCAGTCTATGAAAAGAAGCCCAAGAAAGAAGTTAAAAAGAAGAGGTGGAACCGTCCCAAAATGTCCCTTGCTCAGAAGAAGGATCGGGTAGCTCAAAAGAAGGCAAGCTTCC

**Comment by pmelsted** [comment]
This is a bug, from the name `ENST00000409917_0:788_ENST00000370321_-10:1043` you can see that the second junction point is `-10` which is 10bp before the transcript, so definitely a bug.

**Comment by kmhernan** [comment]
@kreil yes I am seeing this in my unfiltered fasta file with the same kind of negative position offset in the transcript as @pmelsted mentioned

**Comment by pmelsted** [comment]
This bug was fixed in the latest version, 0.37.3.
