### ISSUE TITLE
Failed in installing pizzly

### ISSUE THREAD

**Issue by qindan2008** [pmelsted/pizzly#15]
I tried to install pizzly based on the instructions:
**cmake ..**                                                                                                                                          
-- The CXX compiler identification is GNU 4.9.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /DataProcess/softwares/pizzly/build
 **make**                                                                                                                                               
Scanning dependencies of target pizzly
[ 50%] Building CXX object CMakeFiles/pizzly.dir/main.cpp.o
[100%] Linking CXX executable pizzly
[100%] Built target pizzly
 **sudo make install**                                                                                                          
make: *** Can't create object “install”.  Stop.
So, how couldn't I install pizzly ?

**Comment by pmelsted** [comment]
I didn't make an install rule, will fix.

To install it just copy it to `/usr/local/bin` or any directory that is in your path. You can

**Comment by qindan2008** [comment]
OK, thank you very much.

**Comment by jvivian** [comment]
It might be helpful to update the documentation since it still says to run `make install`, which doesn't work for latest stable release: 96368ca642ed72297ac31e99d0fd77227dd23419
