### ISSUE TITLE
Long read RNA seq

### ISSUE THREAD

**Issue by OxPen** [pmelsted/pizzly#31]
Hello,

I was wondering if kallisto fusion option and pizzly run could run with long reads, such as Nanopore RNA seq data?
I just gave it a try (calculated my avg length of reads at around 500 b and st dev at 5000) but it didn't find any fusions.

Many thanks,

Peny

**Comment by pmelsted** [comment]
No, the fusion detection is based on 1. k-mer matching in kallisto and 2. sequence alignment of potential fusion breakpoints, both of which are unsuitable for the error model of nanopore reads.
