### ISSUE TITLE
No fusion found

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [pmelsted/pizzly#4]
I have a cell line where I know I have  a fusion. No fusion are found.. 

Do you see an error on my command?
```
maurizio@Tardis:~/A_kallisto$ /opt/pizzly -k 31 --gtf ~/Homo_sapiens.GRCh38.79.gtf  --cache ~/Homo_sapiens.GRCh38   --align-score 0 --insert-size 125 --fasta ~/Homo_sapiens.GRCh38.rel79.cdna.all.fa  --output A_fusion fusion.txt 
Opening cached file ... loaded 0 genes and 0 transcripts
Read a total of 173259 transcripts
Number of kept records 0 out of 746328
```

**Comment by pmelsted** [comment]
Sorry for the late reply. The cache behaviour is a bit weird and I need to explain it better.

If the file exists pizzly will reads gene information from it, if it doesn't exist then it parses the gtf and saves it to this file (because parsing the gtf takes much much longer we try to do this only the first time). So `--cache` is both an input and output parameter. 

Also `--align-score` should be set to something greater than 0, perhaps 2 or 3 because this is the number of mismatches pizzly will tolerate when doing full read alignment. 

`--insert-size` should be  an upper bound on the insert size, for regular rna-seq reads I would recomment 250 or so.

**Comment by bioinfo-dirty-jobs** [comment]
I try to use new version of  genome. however I know in that sample there is a  fusion. I don't know why  they don't found. Could you please help me?

```

maurizio@Tardis:~/output$ /opt/pizzly -k 31 --gtf ~/Kallsto_hg38_87/index.gtf --cache ~/Kallsto_hg38_87/index.cache.txt --align-score 3 --insert-size 250 --fasta ~/Kallsto_hg38_87/transcripts.fa --output test fusions.txt
Opening cached file ... loaded 58051 genes and 198002 transcripts
Read a total of 178136 transcripts
Number of kept records 0 out of 0
```



```
 ls -ltr
total 260316
-rw-rw-r-- 1 maurizio maurizio   7417921 mar 28 17:51 abundance.tsv
-rw-rw-r-- 1 maurizio maurizio   2461880 mar 28 17:51 abundance.h5
-rw-rw-r-- 1 maurizio maurizio       361 mar 28 17:51 run_info.json
-rw-rw-r-- 1 maurizio maurizio 256663141 mar 28 17:51 fusion.txt
-rw-rw-r-- 1 maurizio maurizio        22 mar 28 17:58 test.json
-rw-rw-r-- 1 maurizio maurizio         0 mar 28 17:58 test.fusions.fasta
```

**Comment by bioinfo-dirty-jobs** [comment]
Ok Now  seem works however there is man fusion...how can filter?

**Comment by pmelsted** [comment]
We are working on incorporating the filtering directly into pizzly rather than doing it by scripts. The key indicator for good fusion is the amount of reads support, e.g. paircounts or splitcounts.

**Comment by bioinfo-dirty-jobs** [comment]
Thanks so much could you please how to parse the data. 






----Messaggio originale----

Da: "Pall Melsted" <notifications@github.com>

Data: 29/03/2017 17.30

A: "pmelsted/pizzly"<pizzly@noreply.github.com>

Cc: "bioinfo-dirty-jobs"<mauriziopolano@blu.it>, "Author"<author@noreply.github.com>

Ogg: Re: [pmelsted/pizzly] No fusion found (#4)




We are working on incorporating the filtering directly into pizzly rather than doing it by scripts. The key indicator for good fusion is the amount of reads support, e.g. paircounts or splitcounts.

**Comment by pmelsted** [comment]
Here is an example script

```
import json, sys

with open(sys.argv[1]) as f:
    J = json.load(f)

genes = J['genes']
n = len(genes)
todel = []
for i, gp in enumerate(genes):
    numpairs = gp['paircount']
    numsplit = gp['splitcount']

    # require 2 paired reads or at least one split and one paired or two split
    if numpairs < 2 or (numsplit + numpairs) < 2:
        todel.append(i)

for i in todel[::-1]:
    del genes[i] # remove it from the json object

print(json.dumps(J,indent=2))
```

save it to a file `simple_filter.py` and run it with 
```
python simple_filter.py output.unfiltered.json > output.filtered.json
```

**Comment by bioinfo-dirty-jobs** [comment]
Thanks I try to use json from python but gave me some errors


/maurizio/Desktop/kallisto_fusion_annotate.py", line 4, in <module>
    J = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 10 (char 518)





----Messaggio originale----

Da: "Pall Melsted" <notifications@github.com>

Data: 29/03/2017 18.18

A: "pmelsted/pizzly"<pizzly@noreply.github.com>

Cc: "bioinfo-dirty-jobs"<mauriziopolano@blu.it>, "Author"<author@noreply.github.com>

Ogg: Re: [pmelsted/pizzly] No fusion found (#4)




Here is an example script
import json, sys

with open(sys.argv[1]) as f:
    J = json.load(f)

genes = J['genes']
n = len(genes)
todel = []
for i, gp in enumerate(genes):
    numpairs = gp['paircount']
    numsplit = gp['splitcount']

    # require 2 paired reads or at least one split and one paired or two split
    if numpairs < 2 or (numsplit + numpairs) < 2:
        todel.append(i)

for i in todel[::-1]:
    del genes[i] # remove it from the json object

print(json.dumps(J,indent=2))


save it to a file simple_filter.py and run it with
python simple_filter.py output.unfiltered.json > output.filtered.json

**Comment by pmelsted** [comment]
Filtering is now implemented in the latest version.

**Comment by bioinfo-dirty-jobs** [comment]
I try new version. Could you help me to transform the results on tsv. What is the way you suppose we need to use .json file on  choosing  real fusion ?

**Comment by pmelsted** [comment]
There is a python script in the `scripts` folder of the latest release that converts the JSON output to a flat gene based table
