### ISSUE TITLE
Max insert size from Kallisto

### ISSUE THREAD

**Issue by MikeWLloyd** [pmelsted/pizzly#45]
I found issue #5, and the final comment quoted below. The question posed was never answered, and I am also curious about the answer. 

Should I use mean, 95%, or 'max' insert size? If max, what would the calculation be? In #5 there is an argmax statement, would I simply remove '> .95', or would the max calculation be something else? I can't follow what is stored in the matrices, and would appreciate any help. 

              @pmelsted in the command line args it says the "max" value, but do you suggest to instead use the 95th percentile as shown in this script? It is very different from the max value so I wanted to get your input.

_Originally posted by @kmhernan in https://github.com/pmelsted/pizzly/issues/5#issuecomment-315822547_

**Comment by pmelsted** [comment]
The max parameter in pizzly only uses read pairs where the insert size is below the cutoff. My suggestion is to use the 95% of the observed distribution of insert sizes where both reads map concordantly as the cutoff.

**Comment by MikeWLloyd** [comment]
Thank you very much for the clarification! I will move forward with 95%.
