### ISSUE TITLE
no fusion in output files

### ISSUE THREAD

**Issue by doublehelixlf** [pmelsted/pizzly#7]
After a few attempts with our own data (human tumor sample RNAseq) and one set of test data suggested by another user (https://sourceforge.net/projects/fusioncatcher/files/test/), the output file showed 0 record. 

I build kallisto index using the recent gencode.v26 transcriptome file (http://www.gencodegenes.org/releases/current.html). For pizzly, the gtf file was also downloaded from the same link. 

Below is the code running pizzly using the test fastq files (for these files, kallisto run yielded a 1.7MB fusion.txt file): 

pizzly -k 31 --gtf gencode.v26.annotation.gtf --cache v26.cache.txt --align-score 2 --insert-size 250 --fasta gencode.v26.transcripts.fa --output test fusion.txt

And the screen showed:

Opening cached file ... loaded 58219 genes and 199324 transcripts
Read a total of 199166 transcripts
Number of kept records 0 out of 1132

Supposedly, the output file should show what the other user found (https://github.com/pmelsted/pizzly/issues/2).

BTW, I used 
kallisto version: 0.43.1
pizzly version: 0.37.0
SeqAn version: 2.2.0

Not sure what step went wrong. Any suggestion and comment is appreciated.

**Comment by ndaniel** [comment]
I have met this situation too. In my case this happened when `fusion.txt` didn't exist (and there was a typo in the path to `fusion.txt`). It appears that Pizzly does not throw any error/warning when the `fusion.txt` file does not exist.

**Comment by doublehelixlf** [comment]
Thanks ndaniel for the reply. I checked but found no issue with the path to fusion.txt.

The fusion.txt from running kallisto of the test dataset also looks fine. In it, I searched for FGFR3, which showed several cases of SPLIT with both TACC3 and FGFR3, which might indicate fusion of TACC3-FGFR3, as should be in the dataset. One example is shown beloe:
********************************************************
SPLIT	8HT	TTTGCATTCTTCCTCGGCTCCGTGCGGAGTCTCCGCTTTGTGCTGGGACTCTGTCCTGCAAGGGTCTTCTAGGGTCTCAGAGGCGGGTGTCACTCTTCTGT	0,70	8HT	TGGAGGACCTGGACCGTGTCCTTACCGTGACGTCCACCGACACAGAAGAGTGACACCCGCCTCTGAGACCCTAGAAGACCCTTGCAGGACAGAGTCCCAGC	0,10	splitat=(1,41)	(ENST00000484651.5|ENSG00000013810.18|OTTHUMG00000089535.20|OTTHUMT00000358056.1|TACC3-002|TACC3|2715|retained_intron|,801,RC);(ENST00000467746.5|ENSG00000013810.18|OTTHUMG00000089535.20|OTTHUMT00000358058.1|TACC3-004|TACC3|966|nonsense_mediated_decay|,811,RC);(ENST00000313288.8|ENSG00000013810.18|OTTHUMG00000089535.20|OTTHUMT00000203730.2|TACC3-001|TACC3|2781|protein_coding|,781,RC);(ENST00000493975.5|ENSG00000013810.18|OTTHUMG00000089535.20|OTTHUMT00000358059.2|TACC3-005|TACC3|825|protein_coding|,808,RC)	(ENST00000481110.6|ENSG00000068078.17|OTTHUMG00000121148.5|OTTHUMT00000358204.2|FGFR3-006|FGFR3|4217|protein_coding|,2427,FW);(ENST00000340107.8|ENSG00000068078.17|OTTHUMG00000121148.5|-|FGFR3-201|FGFR3|4293|protein_coding|,2496,FW);(ENST00000412135.6|ENSG00000068078.17|OTTHUMG00000121148.5|-|FGFR3-202|FGFR3|3951|protein_coding|,2154,FW);(ENST00000440486.6|ENSG00000068078.17|OTTHUMG00000121148.5|-|FGFR3-203|FGFR3|4287|protein_coding|,2490,FW);(ENST00000613647.4|ENSG00000068078.17|OTTHUMG00000121148.5|-|FGFR3-204|FGFR3|4438|protein_coding|,2641,FW);(ENST00000260795.6|ENSG00000068078.17|OTTHUMG00000121148.5|OTTHUMT00000241632.2|FGFR3-001|FGFR3|4132|protein_coding|,2336,FW);(ENST00000352904.5|ENSG00000068078.17|OTTHUMG00000121148.5|OTTHUMT00000241633.1|FGFR3-002|FGFR3|3733|protein_coding|,1937,FW)
********************************************************

And the jason file is pretty empty, with only the following:

{
  "genes" : [

  ]
}

**Comment by ndaniel** [comment]
Hi doublehelixlf!

Here are the command lines used to run Pizzly on this RNA-seq data set https://sourceforge.net/projects/fusioncatcher/files/test/ which is known to contain the following 17 very well known fusion genes which are shown [here](https://sourceforge.net/projects/fusioncatcher/files/test/readme.txt):

```
wget ftp://ftp.ensembl.org/pub/release-81/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz

wget ftp://ftp.ensembl.org/pub/release-81/gtf/homo_sapiens/Homo_sapiens.GRCh38.81.gtf.gz

wget https://sourceforge.net/projects/fusioncatcher/files/test/reads_1.fq.gz

wget https://sourceforge.net/projects/fusioncatcher/files/test/reads_2.fq.gz

kallisto index -k 31 -i transcriptome.idx  Homo_sapiens.GRCh38.cdna.all.fa.gz

kallisto quant -i transcriptome.idx  -o output_kallisto --fusion  reads_1.fq.gz reads_2.fq.gz

pizzly -k 31 --gtf Homo_sapiens.GRCh38.81.gtf.gz --cache cache.txt  --align-score 2 --insert-size 400 --fasta Homo_sapiens.GRCh38.cdna.all.fa.gz --output output_pizzly output_kallisto/fusion.txt

./show.py output_pizzly.json
```

where the the Python script `show.py` is like this:

```Python
#!/usr/bin/env python

import json, sys

piz = json.load(file(sys.argv[1]))
genes = piz['genes']
i = 0
for gp in genes:
    i = i + 1
    print i,"Fusion:",gp["geneA"]["name"],gp["geneB"]["name"],gp['paircount'],gp['splitcount']
```

The output of Pizzly is here: [output_pizzly.json](https://github.com/pmelsted/pizzly/files/950779/output_pizzly.json.txt).

When running this:
```
./show.py output_pizzly.json
```
it shows for me that Pizzly has found the following fusion genes:
```
1 Fusion: TACC3 FGFR3 487 231
2 Fusion: AKAP9 BRAF 4 4
3 Fusion: FLI1 EWSR1 2 6
4 Fusion: ATF1 EWSR1 3 8
5 Fusion: BRD4 NUTM1 1 6
6 Fusion: ETV6 NTRK3 2 8
7 Fusion: RET HOOK3 2 8
8 Fusion: CD74 ROS1 0 2
```

pizzly version: 0.37.1
SeqAn version: 2.2.0
kallisto 0.43.1

**Comment by doublehelixlf** [comment]
Hi ndaniel,
Thanks for your detailed instruction--appreciate it!
I run the pipeline as you suggested, but got error messages in the last step "./show.py output_pizzly.json".

After a few tries, it looks as though the problem comes from the 0.37.0 version of precompiled binary for linux, as running same code using version 0.37.1  gave the result shown in your post. 

BTW, for the record, after running "./show.py output_pizzly.json", the 0.37.0 version did produce an output_pizzly.jason file. The first entry is the following:

{
  "genes" : [
    {
      "geneA" : { "id" : "ENSG00000013810", "name" : "TACC3"},
      "geneB" : { "id" : "ENSG00000068078", "name" : "FGFR3"},
      "paircount" : 487,
      "splitcount" : 231,
      "transcripts" : [
        {
          "transcriptA": {"id" : "ENST00000340107", "startPos" : 0, "endPos" : 2543, "edit" : 3, "strand" : true},
          "transcriptB": {"id" : "ENST00000458173", "startPos" : 0, "endPos" : 607, "edit" : -86, "strand" : true},
          "support" : 1,
          "reads" : [28, 31, 33, 38, 40, 42, 43, 47, 48, 49, 51, 53, 115, 125, 128, 145, 150, 163, 170, 178, 199, 210, 211, 217, 218, 234, 246, 250, 255, 281, 291, 292, 295, 304, 313, 317, 320, 322, 333, 353, 389, 400, 403, 417, 418, 430, 437, 440, 447, 451, 454, 480, 485, 492, 498, 513, 528, 537, 559, 561, 567, 577, 580, 609, 626, 637, 646, 650, 652, 672, 684, 686, 687, 688, 696, 697, 700, 702, 703, 712, 714]
        },

As far as I can tell, this file differs from the version 0.37.1 run is in the 10th line.
The problematic jason file did not have the following: 

"fasta_record": "ENST00000440486_0:2530_ENST00000612220_461:1756"

And the error message was:
Traceback (most recent call last):
  File "./show.py", line 5, in <module>
    piz = json.load(file(sys.argv[1]))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 4412 column 10 (char 531185)

**Comment by doublehelixlf** [comment]
Hi ndaniel,
Another note: Running (pizzly version: 0.37.1; SeqAn version: 2.2.0; kallisto 0.43.1) using gencode.v26.gtf/fa/idx also seems to be incompatible with ./show.py output_pizzly.json. 

The same pipeline using ensembl.GRCh38 files you suggested worked great. 

Any way, thank you for helping us out!

**Comment by ndaniel** [comment]
Hi doublehelixlf!

I tried to run Pizzly on gencode v26 and now I get **no fusions found**! This is weird. Here are the exact commands which I used:
```
wget ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_26/gencode.v26.annotation.gtf.gz

wget ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_26/gencode.v26.transcripts.fa.gz

wget https://sourceforge.net/projects/fusioncatcher/files/test/reads_1.fq.gz

wget https://sourceforge.net/projects/fusioncatcher/files/test/reads_2.fq.gz

kallisto index -k 31 -i transcriptome.idx  gencode.v26.transcripts.fa.gz

kallisto quant -i transcriptome.idx  -o output_kallisto --fusion  reads_1.fq.gz reads_2.fq.gz

pizzly -k 31 --gtf gencode.v26.annotation.gtf.gz --cache cache.txt  --align-score 2 --insert-size 400 --fasta gencode.v26.transcripts.fa.gz --output output_pizzly output_kallisto/fusion.txt
```
where the file `output_pizzly.json` looks like this:
```
{
  "genes" : [

  ]
}
```
I am confused regarding why Gencode does not work in my hands with Pizzly whilst Ensembl works. 

@doublehelixlf which GTF and FASTA from Gencode file did you use in your case?

pizzly version: 0.37.1
SeqAn version: 2.2.0
kallisto 0.43.1

**Comment by doublehelixlf** [comment]
Hi ndaniel,
Please see two posts above this one. I had the same issue with using gencode.v26. The output_pizzly.jason was empty just like yours!

BTW, I used the same v26 annotation gtf and transcripts as you did.

My guess is that the format of v26.annotation.gtf is somehow different, so that the entries in the output_pizzly.jason file is different from that if using the ensembl gtf. One example was shown in another post yesterday above.

**Comment by doublehelixlf** [comment]
BTW, one difference I noticed in the output_pizzly.jason files using v26 and ensembl annotation files was the following:
One line of:
"fasta_record": "ENST00000440486_0:2530_ENST00000612220_461:1756"

is present in the 10th line of ensembl run output, but is absent in the v26 output.

Can this be a problem for show.py to parse the output_pizzly.jason file?

**Comment by ndaniel** [comment]
So Pizzly states in its [README.MD](https://github.com/pmelsted/pizzly/blob/master/README.md) that 
> We recommend using the Ensembl transcriptomes.

So it looks to me like Genecode transcriptomes (that is Gencode GTF/FASTA files) are not supported by Pizzly (whilst they are supported by Kallisto?). Anyway it would be great to have Pizzly throwing some kind of error/warning when incompatible/unsupported GTF/FASTA files are used.

Regarding the error which you experienced with `show.py`, it appears to me that it is due to an incompatible/corrupted json file being used.

**Comment by doublehelixlf** [comment]
Indeed, saw that as sentence as well. Agree that it could be more strongly worded to prevent any confusion:)

**Comment by pmelsted** [comment]
For some reason the GTF logic is not playing nice with gencode. I'll have to debug and fix this for the next release. In the meantime we **strongly** recommend ensembl
 :)

**Comment by doublehelixlf** [comment]
Thanks Pall for this great tool! 
Looking forward to your new paper on pizzly.

**Comment by kmhernan** [comment]
@pmelsted  Does your substring of the fasta file to remove versioned transcripts play a role in this? see https://github.com/pmelsted/pizzly/blob/master/GeneModel.hpp#L258

I simply can't use anything but the gencode files

UPDATE:

I played around with the source and it is related to this issue of versioned transcripts. So i changed the line pasted above to not substring the `.` version, in addition, the `parseTrList` function needs to be changed to work with gencode:

```
void parseTrList(const std::string &trlist, std::vector<TranscriptPos> &trpos) {
  //std::regex tr_entry("([[:alnum:]]+,-?[[:digit:]]+,[FW|RC]\)")
  std::smatch m;
  auto sre_begin = std::sregex_iterator (trlist.begin(), trlist.end(), trslist_re);
  auto sre_end = std::sregex_iterator();
  for (std::sregex_iterator it = sre_begin; it != sre_end; ++it) {
    auto m = *it;
    TranscriptPos tp;
    std::string chk = m[1];
    std::string vsn = m[2];
    std::string ntr = chk + vsn;
    tp.tr = ntr;
    tp.pos = std::stoi(m[3]);
    tp.strand = (m[4] == "FW") ? Strandedness::FORWARD : Strandedness::REVERSE;
    trpos.push_back(std::move(tp));
  }
}
```

Obviously this isn't generalizable but basically you need to keep the version of the transcript; however, when I did this it worked!

**Comment by pmelsted** [comment]
Hi @kmhernan thanks for spotting this. I'll merge this in with the code so that it can handle gencode as well.

**Comment by kmhernan** [comment]
I'll gladly test with my dataset.

**Comment by arkal** [comment]
+1 Seeing the same issue. I can test as well.

**Comment by pmelsted** [comment]
This has been fixed in the latest release, we now support both Ensembl and Gencode annotations (but you might need to modify the sequence names for Gencode).

Thanks for everyones help in identifying the issues.
